### ISSUE TITLE
Changing Ports

### ISSUE THREAD

**Issue by casesandberg** [payload-app/payload#8]
@hharnisc Do you mind if we change ports for things, maybe go up 100 or something? RN is baked in pretty heavily to `8080` and `8081`. One or the other seems to be running at the same time and wreaking havoc.

**Comment by hharnisc** [comment]
Sounds good to me :smile:

**Comment by hharnisc** [comment]
I'll do this after you've got the `repos-reducx` branch merged in so there isn't a bunch of conflicts to work through! Could do +100 or +1000 -- 9XXX ports are generally pretty good.
